import { Recipe } from '../types';

export const RECIPES_PRIMI: Recipe[] = [
  {
    id: 'pasta_zucchine_pollo',
    name: 'Pasta Zucchine e Pollo',
    category: 'Primi',
    ingredients: ['pasta', 'zucchini', 'chicken_breast'],
    optionalIngredients: ['onion', 'parmesan', 'olive_oil'],
    tags: ['isHighProtein', 'isHighCarb', 'containsGluten'],
    prepTime: 20,
    instructions: "1. Tagliare il pollo e le zucchine a pezzetti.\n2. Rosolare il pollo in padella, poi unire le zucchine.\n3. Cuocere finché teneri.\n4. Unire alla pasta cotta al dente.",
    nutrition: { calories: 500, protein: 30 }
  },
  {
    id: 'risotto_zafferano',
    name: 'Risotto allo Zafferano',
    category: 'Primi',
    ingredients: ['rice', 'onion', 'butter', 'parmesan'],
    optionalIngredients: [],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 30,
    instructions: "1. Soffriggere la cipolla nel burro.\n2. Tostare il riso.\n3. Aggiungere brodo caldo poco alla volta.\n4. Mantecare con parmigiano e zafferano.",
    nutrition: { calories: 450, protein: 10 }
  },
  {
    id: 'pasta_pomodoro',
    name: 'Pasta al Pomodoro',
    category: 'Primi',
    ingredients: ['pasta', 'tomato_sauce', 'olive_oil'],
    optionalIngredients: ['onion', 'garlic', 'parmesan'],
    tags: ['isVegetarian', 'isHighCarb', 'containsGluten', 'isLunchbox'],
    prepTime: 15,
    instructions: "1. Soffriggere aglio e olio.\n2. Aggiungere la passata e cuocere 10 min.\n3. Condire la pasta.",
    nutrition: { calories: 400, protein: 12 }
  },
  {
    id: 'pasta_pesto_patate_fagiolini',
    name: 'Pasta al Pesto, Patate e Fagiolini',
    category: 'Primi',
    ingredients: ['pasta', 'pesto', 'potato', 'green_beans'],
    optionalIngredients: ['parmesan'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose', 'isHighCarb'],
    prepTime: 25,
    instructions: "1. Pelare le patate e tagliarle a cubetti.\n2. Cuocere patate e fagiolini nella stessa acqua della pasta.\n3. Aggiungere la pasta.\n4. Scolare e condire con il pesto.",
    nutrition: { calories: 550, protein: 15 }
  },
  {
    id: 'pasta_ragu',
    name: 'Pasta al Ragù',
    category: 'Primi',
    ingredients: ['pasta', 'minced_meat', 'tomato_sauce', 'onion'],
    optionalIngredients: ['carrots', 'celery', 'olive_oil', 'parmesan'],
    tags: ['isHighProtein', 'isGourmand', 'containsGluten'],
    prepTime: 40,
    instructions: "1. Soffriggere le verdure tritate.\n2. Aggiungere la carne e rosolare.\n3. Unire la passata e cuocere lentamente.\n4. Condire la pasta.",
    nutrition: { calories: 600, protein: 25 }
  },
  {
    id: 'pasta_tonno_cipolla',
    name: 'Pasta Tonno e Cipolla',
    category: 'Primi',
    ingredients: ['pasta', 'tuna_can', 'onion'],
    optionalIngredients: ['olive_oil', 'herbs'],
    tags: ['isHighProtein', 'isLunchbox', 'isHighCarb'],
    prepTime: 15,
    instructions: "1. Soffriggere la cipolla affettata finemente.\n2. Aggiungere il tonno e sfumare.\n3. Saltare la pasta nel condimento.",
    nutrition: { calories: 450, protein: 22 }
  },
  {
    id: 'pasta_boscaiola_rossa',
    name: 'Pasta alla Boscaiola Rossa',
    category: 'Primi',
    ingredients: ['pasta', 'mushrooms', 'tomato_sauce', 'minced_meat'],
    optionalIngredients: ['onion', 'parmesan'],
    tags: ['isGourmand', 'isHighCarb', 'isHighProtein'],
    prepTime: 30,
    instructions: "1. Rosolare la carne e i funghi.\n2. Aggiungere il pomodoro e cuocere per 15 min.\n3. Unire alla pasta.",
    nutrition: { calories: 580, protein: 24 }
  },
  {
    id: 'pasta_norma',
    name: 'Pasta alla Norma',
    category: 'Primi',
    ingredients: ['pasta', 'eggplant', 'tomato_sauce'],
    optionalIngredients: ['mozzarella', 'garlic'],
    tags: ['isVegetarian', 'isGourmand', 'isHighCarb'],
    prepTime: 25,
    instructions: "1. Friggere o rosolare le melanzane a cubetti.\n2. Preparare un sugo semplice di pomodoro.\n3. Unire tutto alla pasta e aggiungere formaggio.",
    nutrition: { calories: 520, protein: 12 }
  },
  {
    id: 'pasta_zucchine_gamberetti',
    name: 'Pasta Zucchine e Gamberetti',
    category: 'Primi',
    ingredients: ['pasta', 'zucchini', 'shrimp'],
    optionalIngredients: ['garlic', 'olive_oil', 'parsley'],
    tags: ['isHighProtein', 'isHighCarb', 'isLunchbox'],
    prepTime: 20,
    instructions: "1. Saltare le zucchine a rondelle.\n2. Aggiungere i gamberetti a fine cottura.\n3. Saltare con la pasta.",
    nutrition: { calories: 420, protein: 25 }
  },
  {
    id: 'pasta_piselli_tacchino',
    name: 'Pasta Piselli e Tacchino',
    category: 'Primi',
    ingredients: ['pasta', 'peas', 'turkey_breast'],
    optionalIngredients: ['onion', 'olive_oil'],
    tags: ['isHighProtein', 'isHighCarb', 'isLunchbox'],
    prepTime: 20,
    instructions: "1. Tagliare il tacchino a cubetti e rosolarlo.\n2. Aggiungere i piselli e un po' d'acqua di cottura.\n3. Condire la pasta.",
    nutrition: { calories: 480, protein: 32 }
  },
  {
    id: 'pasta_piselli',
    name: 'Pasta e Piselli',
    category: 'Primi',
    ingredients: ['pasta', 'peas', 'onion'],
    optionalIngredients: ['parmesan', 'olive_oil'],
    tags: ['isVegetarian', 'isHighCarb', 'isLunchbox'],
    prepTime: 15,
    instructions: "1. Soffriggere la cipolla.\n2. Cuocere i piselli con un mestolo d'acqua.\n3. Frullarne una parte per creare una crema (opzionale) e unire la pasta.",
    nutrition: { calories: 400, protein: 12 }
  },
  {
    id: 'pasta_patate',
    name: 'Pasta e Patate',
    category: 'Primi',
    ingredients: ['pasta', 'potato', 'onion'],
    optionalIngredients: ['carrots', 'celery', 'parmesan'],
    tags: ['isVegetarian', 'isHighCarb', 'isGourmand'],
    prepTime: 25,
    instructions: "1. Tagliare le patate a cubetti piccoli.\n2. Cuocerle nel soffritto aggiungendo acqua calda man mano.\n3. Cuocere la pasta direttamente con le patate.",
    nutrition: { calories: 550, protein: 10 }
  },
  {
    id: 'pasta_fredda_caprese',
    name: 'Pasta Fredda Caprese',
    category: 'Primi',
    ingredients: ['pasta', 'tomatoes', 'mozzarella'],
    optionalIngredients: ['olives', 'herbs', 'olive_oil'],
    tags: ['isVegetarian', 'isLunchbox', 'containsLactose'],
    prepTime: 15,
    instructions: "1. Cuocere la pasta e raffreddarla.\n2. Tagliare pomodori e mozzarella a cubetti.\n3. Condire con olio e basilico.",
    nutrition: { calories: 450, protein: 15 }
  },
  {
    id: 'pasta_ceci',
    name: 'Pasta e Ceci',
    category: 'Primi',
    ingredients: ['pasta', 'chickpeas', 'garlic'],
    optionalIngredients: ['herbs', 'olive_oil', 'tomato_sauce'],
    tags: ['isVegetarian', 'isHighProtein', 'isHighCarb'],
    prepTime: 20,
    instructions: "1. Rosolare l'aglio e unire i ceci.\n2. Schiacciarne una parte.\n3. Cuocere la pasta mista o corta direttamente nel condimento.",
    nutrition: { calories: 480, protein: 18 }
  },
  {
    id: 'pasta_crema_peperoni',
    name: 'Pasta Crema di Peperoni',
    category: 'Primi',
    ingredients: ['pasta', 'peppers', 'onion'],
    optionalIngredients: ['butter', 'parmesan'],
    tags: ['isVegetarian', 'isGourmand'],
    prepTime: 25,
    instructions: "1. Cuocere i peperoni con la cipolla finché teneri.\n2. Frullare tutto per ottenere una crema.\n3. Condire la pasta.",
    nutrition: { calories: 420, protein: 10 }
  },
  {
    id: 'pasta_broccoli_gamberi',
    name: 'Pasta Broccoli e Gamberi',
    category: 'Primi',
    ingredients: ['pasta', 'broccoli', 'shrimp'],
    optionalIngredients: ['garlic', 'chili'],
    tags: ['isHighProtein', 'isHighCarb'],
    prepTime: 20,
    instructions: "1. Sbollentare i broccoli.\n2. Saltare i gamberi con aglio e peperoncino.\n3. Unire i broccoli e la pasta.",
    nutrition: { calories: 440, protein: 26 }
  },
  {
    id: 'carbonara_zucchine',
    name: 'Carbonara di Zucchine',
    category: 'Primi',
    ingredients: ['pasta', 'zucchini', 'eggs', 'parmesan'],
    optionalIngredients: ['onion', 'chili'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 20,
    instructions: "1. Friggere le zucchine a rondelle.\n2. Preparare la crema di uova e formaggio.\n3. Unire la pasta calda alle zucchine e mantecare con le uova fuori dal fuoco.",
    nutrition: { calories: 550, protein: 20 }
  },
  {
    id: 'pasta_gamberetti_piselli_bianca',
    name: 'Pasta Gamberetti e Piselli',
    category: 'Primi',
    ingredients: ['pasta', 'shrimp', 'peas'],
    optionalIngredients: ['onion', 'olive_oil'],
    tags: ['isHighProtein', 'isHighCarb', 'isLunchbox'],
    prepTime: 15,
    instructions: "1. Saltare i piselli con cipolla.\n2. Aggiungere i gamberetti.\n3. Saltare la pasta nel condimento.",
    nutrition: { calories: 430, protein: 24 }
  },
  {
    id: 'pasta_rossa_tonno_piselli',
    name: 'Pasta Rossa Tonno e Piselli',
    category: 'Primi',
    ingredients: ['pasta', 'tomato_sauce', 'tuna_can', 'peas'],
    optionalIngredients: ['onion', 'garlic'],
    tags: ['isHighProtein', 'isHighCarb', 'isLunchbox'],
    prepTime: 20,
    instructions: "1. Fare un sugo con pomodoro e piselli.\n2. Aggiungere il tonno a fine cottura.\n3. Condire la pasta.",
    nutrition: { calories: 460, protein: 25 }
  },
  {
    id: 'pasta_crema_piselli_tacchino',
    name: 'Pasta Crema di Piselli e Tacchino',
    category: 'Primi',
    ingredients: ['pasta', 'peas', 'turkey_breast'],
    optionalIngredients: ['parmesan', 'onion'],
    tags: ['isHighProtein', 'isGourmand'],
    prepTime: 25,
    instructions: "1. Cuocere i piselli e frullarli.\n2. Rosolare il tacchino a striscioline.\n3. Unire tutto alla pasta.",
    nutrition: { calories: 500, protein: 30 }
  },
  {
    id: 'pasta_tonno_zucchine_bianca',
    name: 'Pasta Tonno e Zucchine',
    category: 'Primi',
    ingredients: ['pasta', 'tuna_can', 'zucchini'],
    optionalIngredients: ['onion', 'olive_oil'],
    tags: ['isHighProtein', 'isLunchbox'],
    prepTime: 15,
    instructions: "1. Rosolare le zucchine a cubetti.\n2. Unire il tonno.\n3. Saltare la pasta.",
    nutrition: { calories: 440, protein: 22 }
  },
  {
    id: 'risotto_gamberi_zucchine',
    name: 'Risotto Gamberi e Zucchine',
    category: 'Primi',
    ingredients: ['rice', 'shrimp', 'zucchini'],
    optionalIngredients: ['butter', 'onion'],
    tags: ['isHighProtein', 'isGourmand', 'containsLactose'],
    prepTime: 30,
    instructions: "1. Tostare il riso con la cipolla.\n2. Aggiungere brodo, zucchine e infine gamberi.\n3. Mantecare.",
    nutrition: { calories: 480, protein: 20 }
  },
  {
    id: 'insalata_riso',
    name: 'Insalata di Riso',
    category: 'Primi',
    ingredients: ['rice', 'tuna_can', 'eggs', 'olives', 'tomatoes'],
    optionalIngredients: ['mixed_veg', 'mozzarella'],
    tags: ['isLunchbox', 'isHighCarb', 'containsGluten'],
    prepTime: 20,
    instructions: "1. Bollire il riso e raffreddarlo.\n2. Unire tutti gli ingredienti tagliati a pezzetti.\n3. Condire con olio.",
    nutrition: { calories: 500, protein: 18 }
  },
  {
    id: 'riso_cantonese',
    name: 'Riso alla Cantonese',
    category: 'Primi',
    ingredients: ['rice', 'eggs', 'peas'],
    optionalIngredients: ['minced_meat', 'onion'],
    tags: ['isHighCarb', 'isGourmand'],
    prepTime: 20,
    instructions: "1. Strapazzare le uova.\n2. Saltare riso, piselli e uova in padella (wok) a fuoco alto.",
    nutrition: { calories: 480, protein: 15 }
  },
  {
    id: 'risotto_funghi',
    name: 'Risotto ai Funghi',
    category: 'Primi',
    ingredients: ['rice', 'mushrooms', 'butter', 'parmesan'],
    optionalIngredients: ['onion', 'herbs'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 30,
    instructions: "1. Rosolare i funghi.\n2. Tostare il riso e cuocere con brodo.\n3. Mantecare con burro e parmigiano.",
    nutrition: { calories: 460, protein: 10 }
  },
  {
    id: 'risi_bisi',
    name: 'Risi e Bisi',
    category: 'Primi',
    ingredients: ['rice', 'peas', 'onion', 'parmesan'],
    optionalIngredients: ['butter'],
    tags: ['isVegetarian', 'isHighCarb', 'containsLactose'],
    prepTime: 30,
    instructions: "1. Cuocere i piselli con cipolla.\n2. Aggiungere il riso e portare a cottura come una minestra densa.",
    nutrition: { calories: 420, protein: 12 }
  },
  {
    id: 'riso_forno',
    name: 'Riso al Forno',
    category: 'Primi',
    ingredients: ['rice', 'tomato_sauce', 'mozzarella', 'parmesan'],
    optionalIngredients: ['peas', 'minced_meat'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 45,
    instructions: "1. Condire il riso bollito con sugo e formaggi.\n2. Infornare finché la superficie non è gratinata.",
    nutrition: { calories: 550, protein: 18 }
  },
  {
    id: 'risotto_zucca',
    name: 'Risotto alla Zucca',
    category: 'Primi',
    ingredients: ['rice', 'pumpkin', 'parmesan'],
    optionalIngredients: ['onion', 'butter'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 35,
    instructions: "1. Cuocere la zucca a dadini finché disfatta.\n2. Tostare il riso e cuocere con brodo e zucca.\n3. Mantecare.",
    nutrition: { calories: 440, protein: 10 }
  },
  {
    id: 'insalata_farro',
    name: 'Insalata di Farro',
    category: 'Primi',
    ingredients: ['spelt', 'tomatoes', 'mozzarella', 'olives'],
    optionalIngredients: ['arugula', 'pesto'],
    tags: ['isVegetarian', 'isLunchbox', 'containsLactose'],
    prepTime: 25,
    instructions: "1. Bollire il farro e raffreddare.\n2. Condire con pomodori, mozzarella e olive.\n3. Servire freddo.",
    nutrition: { calories: 400, protein: 15 }
  },
  {
    id: 'couscous_verdure_ceci',
    name: 'Couscous Verdure e Ceci',
    category: 'Primi',
    ingredients: ['couscous', 'zucchini', 'peppers', 'chickpeas'],
    optionalIngredients: ['onion', 'herbs'],
    tags: ['isVegetarian', 'isHighProtein', 'isLunchbox'],
    prepTime: 15,
    instructions: "1. Reidratare il couscous.\n2. Saltare le verdure in padella con i ceci.\n3. Unire tutto e sgranare il couscous.",
    nutrition: { calories: 450, protein: 14 }
  },
  {
    id: 'couscous_pollo_peperoni',
    name: 'Couscous Pollo e Peperoni',
    category: 'Primi',
    ingredients: ['couscous', 'chicken_breast', 'peppers'],
    optionalIngredients: ['onion', 'herbs'],
    tags: ['isHighProtein', 'isLunchbox'],
    prepTime: 20,
    instructions: "1. Saltare pollo e peperoni a tocchetti.\n2. Preparare il couscous.\n3. Unire e condire.",
    nutrition: { calories: 500, protein: 25 }
  },
  {
    id: 'riso_freddo_gamberi_zucchine',
    name: 'Riso Freddo Gamberi e Zucchine',
    category: 'Primi',
    ingredients: ['rice', 'shrimp', 'zucchini'],
    optionalIngredients: ['lemon', 'olive_oil'],
    tags: ['isHighProtein', 'isLunchbox'],
    prepTime: 20,
    instructions: "1. Bollire il riso.\n2. Scottare zucchine e gamberi.\n3. Unire tutto e servire freddo con scorza di limone.",
    nutrition: { calories: 380, protein: 18 }
  },
  {
    id: 'risotto_porri',
    name: 'Risotto ai Porri',
    category: 'Primi',
    ingredients: ['rice', 'leeks', 'parmesan'],
    optionalIngredients: ['butter', 'lemon'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 30,
    instructions: "1. Stufare i porri.\n2. Tostare il riso e cuocere.\n3. Mantecare.",
    nutrition: { calories: 420, protein: 10 }
  },
  {
    id: 'risotto_pomodoro',
    name: 'Risotto al Pomodoro',
    category: 'Primi',
    ingredients: ['rice', 'tomato_sauce', 'parmesan'],
    optionalIngredients: ['mozzarella', 'herbs'],
    tags: ['isVegetarian', 'containsLactose'],
    prepTime: 30,
    instructions: "1. Tostare il riso.\n2. Aggiungere passata e brodo.\n3. Mantecare con parmigiano.",
    nutrition: { calories: 400, protein: 8 }
  },
  {
    id: 'riso_saltato_verdure',
    name: 'Riso Saltato alle Verdure',
    category: 'Primi',
    ingredients: ['rice', 'mixed_veg'],
    optionalIngredients: ['eggs', 'onion'],
    tags: ['isVegetarian', 'isLunchbox'],
    prepTime: 15,
    instructions: "1. Usare riso avanzato o bollito.\n2. Saltare con verdure miste in padella calda.",
    nutrition: { calories: 350, protein: 8 }
  },
  {
    id: 'risotto_asparagi',
    name: 'Risotto agli Asparagi',
    category: 'Primi',
    ingredients: ['rice', 'asparagus', 'parmesan'],
    optionalIngredients: ['butter', 'onion'],
    tags: ['isVegetarian', 'isGourmand', 'containsLactose'],
    prepTime: 35,
    instructions: "1. Usare le punte di asparagi a fine cottura e i gambi nel brodo.\n2. Cuocere il risotto.\n3. Mantecare.",
    nutrition: { calories: 420, protein: 10 }
  },
  {
    id: 'insalata_farro_ceci',
    name: 'Insalata di Farro e Ceci',
    category: 'Primi',
    ingredients: ['spelt', 'chickpeas', 'tomatoes'],
    optionalIngredients: ['arugula', 'olives'],
    tags: ['isVegetarian', 'isHighProtein', 'isLunchbox'],
    prepTime: 20,
    instructions: "1. Bollire il farro.\n2. Unire ceci e pomodori.\n3. Condire con olio e sale.",
    nutrition: { calories: 450, protein: 16 }
  }
];